### ISSUE TITLE
Occasional timeouts when processing relaton

### ISSUE THREAD

**Issue by ribose-jeffreylau** [CalConnect/cc-transcription-systems#85]
# description

Build would *sometimes* fail due to some timeout issues.

# details

See: https://github.com/CalConnect/csd-transcription-systems/runs/2725177196?check_suite_focus=true#step:8:152

```
<snip>
[relaton-gb] ("GB/T 16159-2012") fetching...
bundler: failed to load command: metanorma (/usr/local/bundle/bin/metanorma)
/usr/local/lib/ruby/2.6.0/net/http.rb:947:in `initialize': execution expired (Net::OpenTimeout)
	from /usr/local/lib/ruby/2.6.0/net/http.rb:947:in `open'
	from /usr/local/lib/ruby/2.6.0/net/http.rb:947:in `block in connect'
	from /usr/local/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
	from /usr/local/lib/ruby/2.6.0/net/http.rb:945:in `connect'
	from /usr/local/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
	from /usr/local/lib/ruby/2.6.0/net/http.rb:919:in `start'
	from /usr/local/lib/ruby/2.6.0/open-uri.rb:337:in `open_http'
	from /usr/local/lib/ruby/2.6.0/open-uri.rb:756:in `buffer_open'
	from /usr/local/lib/ruby/2.6.0/open-uri.rb:226:in `block in open_loop'
	from /usr/local/lib/ruby/2.6.0/open-uri.rb:224:in `catch'
	from /usr/local/lib/ruby/2.6.0/open-uri.rb:224:in `open_loop'
	from /usr/local/lib/ruby/2.6.0/open-uri.rb:165:in `open_uri'
<snip>
```

**Comment by ronaldtse** [comment]
@ribose-jeffreylau there is an issue with the GB standards site where it doesn't always connect. But in any case it shouldn't crash. We may have to cache these entries later. Posted to relaton/relaton-gb#37.

**Comment by ribose-jeffreylau** [comment]
@ronaldtse I see, thanks!

**Comment by ribose-jeffreylau** [comment]
Seems issue is not happening.  Closing.
